### ISSUE TITLE
Build Script?

### ISSUE THREAD

**Issue by TroyLDay** [jfcaiceo/react-lightbox-component#4]
I built the dist folder using gulp build, however, the /lib directory is missing that is present when downloading from npm.  The /lib files seem to be the ones that are used, so is there a separate build process or build script that should be used? My goal is to use build and use my fork while the pull request is unmerged. Kind Thanks!

**Comment by jfcaiceo** [comment]
That script is in the package.json (scripts => build):
`babel --presets es2015,react src/ --out-dir lib/`

**Comment by TroyLDay** [comment]
Thanks for adding!
